export enum TipoServico {
    BANHO_TOSA = 'BANHO e TOSA',
    CONSULTA = 'CONSULTA VETERINÁRIA',
    LEVA_TRAZ = 'LEVA e TRAZ',
    // ENSAIO_FOTOGRAFICO = 'ENSAIO_FOTOGRAFICO',
    // SPA = 'SPA',
    // MICROCHIPAGEM = 'MICROCHIPAGEM',
    // VACINACAO = 'VACINACAO',
    // CONSULTAS = 'CONSULTAS',
    // ESCOVACAO = 'ESCOVACAO',
    // CORTE_UNHAS = 'CORTE_UNHAS',
    // COLORACAO = 'COLORACAO',
}
