export enum TipoServico {
    BANHO = 'BANHO',
    TOSA = 'TOSA',
    LEVA_TRAZ = 'LEVA_TRAZ',
    ENSAIO_FOTOGRAFICO = 'ENSAIO_FOTOGRAFICO',
    SPA = 'SPA',
    MICROCHIPAGEM = 'MICROCHIPAGEM',
    VACINACAO = 'VACINACAO',
    CONSULTAS = 'CONSULTAS',
    ESCOVACAO = 'ESCOVACAO',
    CORTE_UNHAS = 'CORTE_UNHAS',
    COLORACAO = 'COLORACAO',
}
