export enum TipoServico {
    BANHO_TOSA = 'BANHO e TOSA',
    CONSULTA = 'CONSULTA VETERINÁRIA',
    LEVA_TRAZ = 'LEVA e TRAZ',
    // ENSAIO_FOTOGRAFICO = 'ENSAIO FOTOGRAFICO',
    // SPA = 'SPA',
    // MICROCHIPAGEM = 'MICROCHIPAGEM',
    // VACINACAO = 'VACINAÇÃO',
    // CONSULTAS = 'CONSULTAS',
    // ESCOVACAO = 'ESCOVAÇÃO',
    // CORTE_UNHAS = 'CORTE de UNHAS',
    // COLORACAO = 'COLORAÇÃO', 
}
