GET http://localhost:3000

### Cadastrar Cliente 
POST http://localhost:3000/cliente
Content-Type: application/json

{
    "nome_cliente": "Girotto",
    "cpf_cliente": "12345679",
    "email_cliente": "jrgirotto@gmail.com",
    "telefone_cliente": "11997779977",
    "endereco_cliente": "Rua: Edmundo"
}

### Cadastrar Pet 
POST http://localhost:3000/pet
Content-Type: application/json

{
    "name": "Meg",
    "especie": "cachorro",
    "raca": "Caramelo",
    "clienteId": "4d946256-99c4-452a-9944-b6d45765d840"
}

POST http://localhost:3000/petshop
Content-Type: application/json

{
    "nome_cliente": "Junior",
    "cpf_cliente": "1234567",
    "email_cliente": "jr@gmail.com",
    "telefone_cliente": "11997779977",
    "endereco_cliente": "Rua: Edmundo"
}